### ISSUE TITLE
ModuleNotFoundError: No module named 'playwright'

### ISSUE THREAD

**Issue by Eythynhkh** [gravelBridge/AutoGPT_Web_Interaction_Plugin#8]
ModuleNotFoundError: No module named 'playwright'

so i posted this error to chatgpt and it said i need to install the 'playwright' module using pip, the Python package installer.

"pip install playwright"
"playwright install"

so i done that and i got the same error. i told chat-gpt and it said -

"My apologies for the confusion, as an AI model, I'm unable to execute Python code or directly interact with your Python environment to check if the module is installed correctly. However, you can check if the Playwright module is installed correctly by running the following command in your Python environment:

python -c "import playwright"

If the command does not output any message, it means that the Playwright module is correctly installed. If it outputs an error message like ModuleNotFoundError: No module named 'playwright', it means that the Playwright module is not installed correctly."

the command does not output any messages but im still getting the same error

**Comment by Eythynhkh** [comment]
(sorry my post doesnt make any sense so ive edited it so now it does)

ModuleNotFoundError: No module named 'playwright'

so i posted this error to chatgpt and it said i need to install the 'playwright' module using pip, the Python package installer.

"pip install playwright"
"playwright install"

so i done that and i got the same error. i told chat-gpt and it said - 

"My apologies for the confusion, as an AI model, I'm unable to execute Python code or directly interact with your Python environment to check if the module is installed correctly. However, you can check if the Playwright module is installed correctly by running the following command in your Python environment:

python -c "import playwright"

If the command does not output any message, it means that the Playwright module is correctly installed. If it outputs an error message like ModuleNotFoundError: No module named 'playwright', it means that the Playwright module is not installed correctly."

the command does not output any messages but im still getting the same error

**Comment by KingSamuelDavid** [comment]
you need to install, tbh should be on the readme doc to install first this also. I think editing the readme to include this step is acceptable and this ticket can be closed.
